name: puncher
description: puncher is a flutter package that helps you to create a puncher widget.
version: 0.0.4
homepage: https://github.com/physia/kflutter
repository: https://github.com/physia/kflutter

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shaper: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

screenshots:
  - description: 'puncher is a flutter package that helps you to create a puncher widget.'
    path: pub_screenshots/screenshot.png
