name: flutter_map_cached_tile_provider
description: "cached tile provider for flutter_map"
version: 0.0.3
homepage: https://github.com/physia/kflutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  cached_network_image_platform_interface: ^4.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.3
  flutter_map: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
